FROM --platform=${BUILDPLATFORM} tonistiigi/xx:master@sha256:7d5cbcc2c24fd4af0b555e51e7ff7282aad6d8a56275e06681a209237fd0becd AS xx
FROM --platform=${BUILDPLATFORM} crazymax/osxcross:latest-alpine@sha256:ab016ff172118c7c98f49413bbdbf496b7c96c2677d1fb1736543301b8359341 AS osxcross
FROM --platform=${BUILDPLATFORM} alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375

COPY --from=xx / /
COPY --from=osxcross / /
RUN \
    ln -s /osxcross/SDK /xx-sdk && \
    apk add --no-cache \
        autoconf \
        automake \
        bash \
        binutils \
        clang \
        clang-analyzer \
        clang-bash-completion \
        clang-ccache \
        clang-extra-tools \
        cmake \
        compiler-rt \
        curl \
        file \
        g++ \
        gcc \
        git \
        i686-mingw-w64-gcc \
        libtool \
        lld \
        llvm \
        make \
        mingw-w64-gcc \
        ninja-build \
        ninja-is-really-ninja \
        patch \
        perl \
        pkgconf \
        powershell \
        unzip \
        zip

ENV \
    VCPKG_FORCE_SYSTEM_BINARIES=1 \
    VCPKG_DISABLE_METRICS=1

RUN \
    git clone https://github.com/microsoft/vcpkg.git /vcpkg && \
    cd /vcpkg && \
    ./bootstrap-vcpkg.sh -disableMetrics && \
    ln -s /vcpkg/vcpkg /usr/local/bin/vcpkg

ENV VCPKG_ROOT=/vcpkg

RUN \
    for i in linux/arm linux/arm64 linux/386 linux/amd64; do \
        TARGETPLATFORM="${i}" xx-clang --setup-target-triple; \
        TARGETPLATFORM="${i}" xx-apk add --no-cache g++ gcc libc++ libc++-dev libc++-static libc-dev linux-headers; \
    done

RUN \
    for i in windows/386 windows/amd64 darwin/arm64 darwin/amd64; do \
        TARGETPLATFORM="${i}" xx-clang --setup-target-triple; \
    done; \
    echo "-fuse-ld=ld" >> /usr/bin/i686-w64-mingw32.cfg && \
    ln -s /osxcross/bin/x86_64-apple-darwin23.6-otool /usr/local/bin/otool; \
    ln -s /osxcross/bin/x86_64-apple-darwin23.6-install_name_tool /usr/local/bin/install_name_tool

COPY vcpkg-custom-triplets /vcpkg-custom-triplets
ENV VCPKG_OVERLAY_TRIPLETS=/vcpkg-custom-triplets

WORKDIR /src
