find_program(CMAKE_ADDR2LINE                    NAMES "${triplet}-addr2line" REQUIRED)
find_program(CMAKE_AR                           NAMES "${triplet}-ar" REQUIRED)
find_program(CMAKE_ASM_COMPILER                 NAMES "${triplet}-as" REQUIRED)
find_program(CMAKE_CXX_COMPILER                 NAMES "${triplet}-clang++" REQUIRED)
find_program(CMAKE_C_COMPILER                   NAMES "${triplet}-clang" REQUIRED)
find_program(CMAKE_DLLTOOL                      NAMES "${triplet}-dlltool" REQUIRED)
find_program(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS NAMES "clang-scan-deps" REQUIRED)
find_program(CMAKE_NM                           NAMES "${triplet}-nm" REQUIRED)
find_program(CMAKE_OBJCOPY                      NAMES "llvm-objcopy" REQUIRED)
find_program(CMAKE_OBJDUMP                      NAMES "llvm-objdump" REQUIRED)
find_program(CMAKE_NM                           NAMES "${triplet}-nm" REQUIRED)
find_program(CMAKE_RANLIB                       NAMES "${triplet}-ranlib" REQUIRED)
find_program(CMAKE_READELF                      NAMES "${triplet}-readelf" REQUIRED)
find_program(CMAKE_STRIP                        NAMES "${triplet}-strip" REQUIRED)

foreach(lang ASM C CXX)
    set(CMAKE_${lang}_COMPILER_TARGET "${triplet}" CACHE STRING "")
    set(CMAKE_${lang}_COMPILER_AR     "${CMAKE_AR}" CACHE STRING "")
    set(CMAKE_${lang}_COMPILER_RANLIB "${CMAKE_RANLIB}" CACHE STRING "")
endforeach()
